# Generated by Django 3.2.4 on 2021-06-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_listingstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='startprice',
            field=models.FloatField(default='1.0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingstatus',
            name='description',
            field=models.CharField(default='hello', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
