# Generated by Django 3.2.4 on 2021-06-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210619_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='imageurl',
            field=models.URLField(default='https://via.placeholder.com/150/'),
            preserve_default=False,
        ),
    ]
