# Generated by Django 3.2.4 on 2021-06-19 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210619_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='auctions.category'),
        ),
    ]
