# Generated by Django 3.2.4 on 2021-06-19 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='creator',
            field=models.CharField(blank=True, default='superman', max_length=80),
        ),
        migrations.AlterField(
            model_name='listing',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
