# Generated by Django 3.2.4 on 2021-06-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210620_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ebay_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
