# Generated by Django 3.2.4 on 2021-06-24 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_bid_bidder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='bidder',
            new_name='author',
        ),
    ]
