# Generated by Django 3.2.4 on 2021-06-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20210624_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
